fail_fast: true
minimum_pre_commit_version: '1.16.1'
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.2.1
      hooks:
          - id: check-added-large-files
            args: ['--maxkb=400']
            exclude: \.ipynb$
          - id: check-ast
          - id: check-docstring-first
          - id: check-executables-have-shebangs
          - id: check-json
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-yaml
          - id: debug-statements
          - id: fix-encoding-pragma
          - id: trailing-whitespace
    - repo: local
      hooks:
          - id: no-autoflake-clean
            name: no-autoflake-clean
            entry: clean_ipynb --no-autoflake
            language: system
            files: (__init__|common)\.py$
          - id: only-black
            name: only-black
            entry: clean_ipynb --no-autoflake --no-isort
            language: system
            files: specific\.py$
          - id: python-clean
            name: python-clean
            entry: clean_ipynb --no-ipynb
            language: system
            files: \.py$
            exclude: (__init__|common|specific)\.py$
          - id: jupyter-clean
            name: jupyter-clean
            entry: clean_ipynb --no-py --no-autoflake --keep-output
            language: system
            files: \.ipynb$
            # - id: pytest
            #   name: pytest
            #   entry: pytest -v -rs -m "not slow" --ignore-glob='joblib/**/func_code.py'
            #   pass_filenames: false
            #   language: system
            #   verbose: true
